### ISSUE TITLE
UCI time + increment function

### ISSUE THREAD

**Issue by tissatussa** [Checkmate6659/seredina-chess#1]
hi, i just discovered your Seredina v1.2 engine and I managed to compile it on Linux (Xubuntu 22.04) - the engine seems rather strong !

But i have to set special time settings to make it play a good game : in CuteChess (GUI) i see it always uses the "winc" / "binc" time to think, this is the bonus time !? E.g. when i set 5 minutes + 3 seconds bonus for a game, it only uses the 3 seconds (3.1 to be exact) for each move, so it keeps having about 5 minutes until the end of the game. This is not normal, you should change that.

Another thing : often it shows an eval value of "+21474836.47" or alike, which is much too high - this is strange.

Are you aware of these ? Can you fix it ?

**Comment by Checkmate6659** [comment]
Both bugs are fixed in release 1.2b
I actually didn't know that high cp values would break things... I clamped them between -9999 and 9999

**Comment by tissatussa** [comment]
@Checkmate6659
The time issue seems solved but the high cp values are not, see this screencast of CuteChess GUI (6 minutes long) :

https://github.com/user-attachments/assets/75b6b43f-81b6-489e-805e-5a66449f9b8f

It's the first part of this game.
We see at moves 2, 11 and 18 the cp value is "normal", all other moves show "+99.99", but not during the evaluation !?
Something's still wrong ..

```
[Event "engine vs engine"]
[Site "Holland"]
[Date "2025.01.18"]
[Round "?"]
[White "Seredina v1.2b NNUE"]
[Black "XoRoN"]
[Result "1-0"]
[ECO "B00"]
[GameDuration "00:12:56"]
[Opening "King's pawn"]
[PlyCount "103"]
[TimeControl "300+3"]
[Variation "Nimzowitsch defense"]

1. e4 {+99.99/18 13s} Nc6 {-0.14/11 10s} 2. d4 {+0.79/19 13s} d5 {-0.08/11 10s}
3. exd5 {+99.99/19 12s} Qxd5 {-0.04/11 10s} 4. Nf3 {+99.99/19 12s}
Nb4 {-0.17/10 9.9s} 5. a3 {+99.99/17 12s} Qe4+ {-0.47/11 9.8s}
6. Kd2 {+99.99/17 11s} Qf4+ {-0.36/11 9.6s} 7. Kc3 {+99.99/18 11s}
Nd5+ {-0.56/11 9.4s} 8. Kb3 {+99.99/20 11s} Qd6 {-0.46/11 9.3s}
9. c4 {+99.99/20 11s} Nf4 {-0.67/10 9.1s} 10. Nc3 {+99.99/18 10s}
a6 {-0.70/9 9.0s} 11. Ne4 {+3.74/16 10s} Qb6+ {-0.98/10 8.8s}
12. Ka2 {+99.99/17 9.9s} Nf6 {-1.05/11 8.7s} 13. Nxf6+ {+99.99/17 9.7s}
Qxf6 {-0.62/11 8.5s} 14. Be3 {+99.99/19 9.5s} Bg4 {-0.64/10 8.4s}
15. h3 {+99.99/17 9.3s} Bh5 {-0.96/11 8.3s} 16. g4 {+99.99/17 9.0s}
Bg6 {-1.21/11 8.1s} 17. Ne5 {+99.99/19 8.8s} Be4 {-1.41/11 8.0s}
18. f3 {+6.78/18 8.7s} Bc6 {-1.87/12 7.9s} 19. g5 {+99.99/18 8.5s}
Qf5 {-1.96/12 7.7s} 20. Nxc6 {+99.99/19 8.3s} bxc6 {-2.00/11 7.6s}
21. Qa4 {+6.81/19 8.1s} Kd7 {-1.81/11 7.5s} 22. d5 {+99.99/19 7.9s}
Kd8 {-1.83/11 7.4s} 23. Qxc6 {+99.99/19 7.8s} Rb8 {-2.17/11 7.3s}
24. Ba7 {+99.99/20 7.6s} Rc8 {-2.21/11 7.2s} 25. Rd1 {+10.26/16 7.5s}
Qc2 {-2.39/10 7.1s} 26. Rd4 {+12.00/15 7.3s} Qf5 {-3.10/11 7.0s}
27. c5 {+99.99/19 7.2s} Qe5 {-3.32/11 6.9s} 28. Rxf4 {+99.99/21 7.0s}
e6 {-7.58/11 6.8s} 29. Bxa6 {+36.22/16 6.9s} Qxd5+ {-8.28/12 6.7s}
30. Qxd5+ {+37.93/15 6.8s} exd5 {-8.80/13 6.6s} 31. Rd1 {+99.99/20 6.6s}
Ra8 {-8.65/12 6.5s} 32. Rxd5+ {+41.42/17 6.5s} Bd6 {-8.74/13 6.4s}
33. Rxf7 {+99.99/20 6.4s} Rxa7 {-8.81/12 6.3s} 34. Bb5 {+45.41/19 6.3s}
Kc8 {-10.13/12 6.2s} 35. cxd6 {+99.99/20 6.2s} Kb7 {-11.22/12 6.2s}
36. dxc7 {+49.99/18 6.1s} Rc8 {-10.24/12 6.1s} 37. Rd6 {+55.29/17 6.0s}
Rxc7 {-10.36/12 6.0s} 38. Ba6+ {+57.11/17 5.9s} Rxa6 {-10.70/14 5.9s}
39. Rxc7+ {+58.85/19 5.8s} Kxc7 {-10.74/13 5.9s} 40. Rxa6 {+58.85/19 5.7s}
Kd7 {-12.08/12 5.8s} 41. Ra7+ {+63.23/15 5.6s} Ke6 {-12.08/11 5.7s}
42. Rxg7 {+63.80/16 5.5s} Kf5 {-18.20/11 5.7s} 43. h4 {+65.32/16 5.4s}
Ke5 {-19.46/11 5.6s} 44. Rxh7 {+74.98/17 5.3s} Kf4 {-20.87/11 5.5s}
45. g6 {+88.14/14 5.3s} Kxf3 {-M14/11 5.5s} 46. g7 {+99.99/14 5.2s}
Kf4 {-M12/9 5.4s} 47. g8=Q {+99.99/13 5.1s} Ke5 {-M8/8 5.3s}
48. Re7+ {+99.99/11 5.0s} Kd6 {-M8/8 5.3s} 49. Qe6+ {+99.99/13 5.0s}
Kc5 {-M6/8 5.2s} 50. Rc7+ {+99.99/14 4.9s} Kd4 {-M4/7 5.2s}
51. Kb1 {+99.99/14 4.8s} Kd3 {-M2/7 5.1s} 52. Rd7# {+99.99/15 4.8s, White mates}
1-0
```

**Comment by rwbc** [comment]
Yes, the problem was not only the overflow, but that it shows a max score value (out of the blue and detached from teh position) often for the last pv before best move and this is sent to the pgn ofc.

My win (gcc for now, trying clang later) compilation, which wasn't as easy as expected. Actually I forgot what I had changed to compile in msys2 from my compilation in July 2024 (which doesn't use posix but some way to circumvent it for crosscompiling).
But I tell you more via email in our conversation and how to proceed.

**new compilation**
```
id name Seredina v1.2b
id author Enigma
option name Hash type spin default 16 min 1 max 1024
uciok
isready
readyok
position startpos
go wtime 120000 btime 120000 winc 1000 binc 1000
info depth 1 score cp 50 nodes 20 time 1 nps 20000 pv d2d4
info depth 2 score cp 52 nodes 100 time 2 nps 50000 pv e2e4 e7e5
info depth 3 score cp 65 nodes 236 time 3 nps 78666 pv e2e4 d7d5 e4d5 d8d5
info depth 4 score cp 65 nodes 492 time 4 nps 123000 pv e2e4 d7d5 e4d5 d8d5
info depth 5 score cp 40 nodes 1521 time 6 nps 253500 pv e2e4 e7e6 d2d4 d7d5 e4d5
info depth 6 score cp 67 nodes 3079 time 10 nps 307900 pv e2e4 c7c5 d2d4 c5d4 d1d4 g8f6
info depth 7 score cp 39 nodes 14718 time 24 nps 613250 pv d2d4 e7e6 e2e3 d7d5 c2c4 d5c4 f1c4
info depth 8 score cp 53 nodes 28090 time 38 nps 739210 pv e2e4 e7e6 d2d4 d7d5 b1d2 c7c5 g1f3 c5d4 e4d5
info depth 9 score cp 59 nodes 93232 time 98 nps 951346 pv e2e4 e7e6 d2d4 d7d5 b1c3 d5e4 c3e4 d8d5 d1f3 d5d4
info depth 10 score cp 45 nodes 151364 time 156 nps 970282 pv e2e4 e7e6 d2d4 d7d5 e4e5 c7c5
info depth 11 score cp 51 nodes 221659 time 221 nps 1002981 pv e2e4 e7e6 d2d4 d7d5 b1d2 c7c5 e4d5 e6d5 d1e2 c8e6 e2b5 b8c6 d4c5 a8c8
info depth 12 score cp 53 nodes 410909 time 393 nps 1045569 pv e2e4 e7e5 b1c3 g8f6 g1f3 b8c6 d2d4 f8b4 d4e5 b4c3 b2c3 f6e4 f1d3 e4c3
info depth 13 score cp 40 nodes 802049 time 749 nps 1070826 pv e2e4 e7e5 g1f3 b8c6 d2d4 e5d4 f3d4 g8f6 d4c6 b7c6 f1d3 d7d5 b1c3 d5e4 c3e4 f6e4 d3e4 d8d1 e1d1
info depth 14 score cp 51 nodes 1290763 time 1184 nps 1090171 pv e2e4 e7e5 g1f3 g8f6
info depth 15 score cp 51 nodes 1988164 time 1803 nps 1102697 pv e2e4 e7e5 g1f3 g8f6
info depth 16 score cp 53 nodes 4824283 time 4321 nps 1116473 pv e2e4 e7e5 g1f3 b8c6 d2d4
info depth 17 score cp 9999 nodes 5533696 time 4952 nps 1117466 pv e2e4 d7d5 e4d5
bestmove e2e4
```
**old compilation**
```
uci
id name Seredina v1.2
id author Enigma
option name Hash type spin default 16 min 1 max 1024
uciok
isready
readyok
position startpos
go wtime 120000 btime 120000 winc 1000 binc 1000
info depth 1 score cp 50 nodes 20 time 2 nps 10000 pv d2d4
info depth 2 score cp 52 nodes 100 time 3 nps 33333 pv e2e4 e7e5
info depth 3 score cp 65 nodes 236 time 3 nps 78666 pv e2e4 d7d5 e4d5 d8d5
info depth 4 score cp 65 nodes 492 time 5 nps 98400 pv e2e4 d7d5 e4d5 d8d5
info depth 5 score cp 40 nodes 1521 time 7 nps 217285 pv e2e4 e7e6 d2d4 d7d5 e4d5
info depth 6 score cp 67 nodes 3079 time 10 nps 307900 pv e2e4 c7c5 d2d4 c5d4 d1d4 g8f6
info depth 7 score cp 39 nodes 14718 time 26 nps 566076 pv d2d4 e7e6 e2e3 d7d5 c2c4 d5c4 f1c4
info depth 8 score cp 53 nodes 28090 time 39 nps 720256 pv e2e4 e7e6 d2d4 d7d5 b1d2 c7c5 g1f3 c5d4 e4d5
info depth 9 score cp 59 nodes 93232 time 103 nps 905165 pv e2e4 e7e6 d2d4 d7d5 b1c3 d5e4 c3e4 d8d5 d1f3 d5d4
info depth 10 score cp 45 nodes 151364 time 159 nps 951974 pv e2e4 e7e6 d2d4 d7d5 e4e5 c7c5
info depth 11 score cp 51 nodes 221659 time 223 nps 993986 pv e2e4 e7e6 d2d4 d7d5 b1d2 c7c5 e4d5 e6d5 d1e2 c8e6 e2b5 b8c6 d4c5 a8c8
info depth 12 score cp 53 nodes 410909 time 397 nps 1035035 pv e2e4 e7e5 b1c3 g8f6 g1f3 b8c6 d2d4 f8b4 d4e5 b4c3 b2c3 f6e4 f1d3 e4c3
info depth 13 score cp 40 nodes 802049 time 753 nps 1065138 pv e2e4 e7e5 g1f3 b8c6 d2d4 e5d4 f3d4 g8f6 d4c6 b7c6 f1d3 d7d5 b1c3 d5e4 c3e4 f6e4 d3e4 d8d1 e1d1
info depth 14 score cp 2147483647 nodes 1150976 time 1071 nps 1074674 pv e2e4 e7e6 d2d4
bestmove e2e4
```

**Comment by rwbc** [comment]
BTW I get this warning?

```
search.cpp: In function 'chess::Move search_root(W_Board&, int, int)':
search.cpp:454:53: warning: overflow in conversion from 'uint64_t' {aka 'long long unsigned int'} to 'clock_t' {aka 'long int'} changes value from '9223372036854775807' to '-1' [-Woverflow]
  454 |         search_end_time = (uint64_t)((clock_t)(-1)) >> 1; //maximum value of a clock_t
      |                           ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~

```

**Comment by Checkmate6659** [comment]
I fixed the bogus scores being shown at the end of the search, and updated the 1.2b release
Ive also implemented 32-bit clock compatibility (supposing we don't run the engine for 25 days straight without restarting it), but didn't test it, so it's just the latest commit in the main branch right now (f84c8c2)

**Comment by tissatussa** [comment]
> ..implemented 32-bit clock compatibility..

i never heard of that, but it seems OK.

i will test the new v1.2b soon and let you know my findings here.
btw. maybe you should've used v1.2c for this .. never mind.

another thing : your engine isn't (yet) listed in the CCRL lists, but i estimate its rating is about 3000. What's your guess ?

**Comment by tissatussa** [comment]
@Checkmate6659 indeed the new v1.2b fixed the "bogus score" cp values !

**Comment by rwbc** [comment]
Regrettably windows compilation in msys2 remains bogus for another reason, which already was there in my first compilation, in July 2024, but meanwhile I forgot about it and had to re-learn the hard way today.

Already in the first test game it caused a severe problem on my quite new computer, so I had to disconnect it from power as nothing worked anymore, until a kind of Black Screen... Event history says it grabbed all available memory alone (32GB Ram).

A quick retest confirmed that my compilation uses around 200MB more per each second! I guess I need to find one, who still uses
old cygwin and then it might reveal, if the compilation is the issue or win behaviour generally...

**Comment by Checkmate6659** [comment]
The memory leak should be fixed now, I've also set up a quick windows build environment.
However I found the windows builds quite a bit slower than the Linux builds, but it isn't easy to compare, since the whole environment is different; the Windows builds also use G++ instead of Clang++.

Maybe this issue should be open instead, since it's full of... well... issues.

**Comment by rwbc** [comment]
I see you have now fixed everything w/o me sending the changes. We experienced that clang compilations for Seredina will
always segfault with the flto flag but even w/o using it they were around 20% faster.
Your gcc compilation is around the same speed as mine here on win.

I have not yet tried to compile your updated sources. And yes the use of 'new' was the problem in order.hpp.

**Comment by rwbc** [comment]
[seredina_12c-clang.zip](https://github.com/user-attachments/files/18497229/seredina_12c-clang.zip)

OK, current source compiles now with no problems anymore!
It's more like a 10% difference in favour of the clang compilation now.

Here is the bench output from 5 fresh runs for the two diff. compilations (deleted prefetch entries before starting a bench script)

**clang vs. your offical avx2 gcc release version on Ryzen7 5700G Win11Pro**
```
489358 nodes 1941896 nps
489358 nodes 1729180 nps

489358 nodes 1973217 nps
489358 nodes 1717045 nps

489358 nodes 1934221 nps
489358 nodes 1747707 nps

489358 nodes 1957432 nps
489358 nodes 1747707 nps

489358 nodes 1904116 nps
489358 nodes 1747707 nps
```

**Comment by SzotsGabor** [comment]
I have successfuly compiled the 1.2c source using "clang++ -std=c++17 -O3 -s -DNDEBUG -march=native -ffast-math -fno-signed-zeros *.cpp" as the command line.
The result is slightly faster than the exe you provided but I am using yours anyway. Started a gauntlet for the CCRL blitz list.

Gabor Szots
CCRL testinggroup
